### ISSUE TITLE
Handle bad sqllite setup in REST message on ingest

### ISSUE THREAD

**Issue by dhutchis** [uwescience/myria#841] opened 2016-08-09 05:17 UTC
When sqllite is not working properly, [this line in the `getDatasetStatus` method](../blob/master/src/edu/washington/escience/myria/coordinator/MasterCatalog.java#L1325) could return null.  In this case, the REST call for ingesting a dataset returns a NullPointerException and the user has no idea what went wrong.  I'm still not sure why sqllite is having trouble.  I encountered this when running Myria on my laptop and ingesting a dataset through the [`newDatasetMultipart` method](https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/api/DatasetResource.java#L518).

**Comment by dhutchis** [comment] 2016-08-11 04:19
Anyone know the cause of this? It popped up again for me, this time on a Myria cluster that used to work fine.  More generally, how do we look at the SQLite that Myria stores catalog information inside?

**Comment by jortiz16** [comment] 2016-08-11 16:07
Hey Dylan, I would also recommend looking at the catalog and running the query that returns a null response. You can view the catalog by looking for the ```master.catalog``` file under the myria directory and open with ```sqlite3 master.catalog```.

I'm not yet sure why an ingest would return a NullPointer, can you give more details about the error you get here?....If these ingests are failing, then the ```datasetStatus``` would not have anything to return.

**Comment by dhutchis** [comment] 2016-08-11 19:17
Hi @jortiz16, I can't find the `master.catalog` file in the myria deployment location. I tried `find . -name master.catalog`.

According to the code, the null pointer is a result of the SQLite query not returning any results.

**Comment by BrandonHaynes** [comment] 2016-08-11 19:21
Irrespective of the underlying cause of this error, it seems like we should be throwing a CatalogException if the relation isn't found in SQLite.

**Comment by jingjingwang** [comment] 2016-08-11 20:25
Returning null at https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/coordinator/MasterCatalog.java#L1325 is the correct behavior, since we return 404 if the result is null: https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/api/DatasetResource.java#L110. So I don't think the above line is the cause of your `NullPointerException`.

**Comment by dhutchis** [comment] 2016-08-11 20:31
@jingjingwang This line throws the NullPointerException. It is called when a new dataset is ingested.  

https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/api/DatasetResource.java#L616

**Comment by jortiz16** [comment] 2016-08-11 20:46
Can you provide the full stack trace? Seems like ```status``` variable is null, implying that that server.ingestDataset() failed at some point

**Comment by dhutchis** [comment] 2016-08-11 20:49
@jortiz16 The status variable is null as a result of this line:

https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/coordinator/MasterCatalog.java#L1325

**Comment by jingjingwang** [comment] 2016-08-11 21:06
I see, for some reason the ingestion failed and `getDatasetStatus` returns null, but it's not handled in `doIngest`. I think we should at least check that in `doIngest`. Meanwhile why the ingestion failed to insert an entry? Could you check the table in the master catalog? The catalog should be in the master's working directory, as specified in "path" in `deployment.cfg`.

**Comment by jingjingwang** [comment] 2016-08-11 21:09
Also logs during ingestion may be helpful. If you still can't find `master.catalog`, try a new deployment at some other place. (any chance that the disk was full?)

**Comment by dhutchis** [comment] 2016-08-11 21:10
Yep, I found the master.catalog now. It does not have an entry for the new table in either the `relations` table or `stored_relations` table. Yet the ingest returns success.  Same phenomena happens when I create a new relation as the result of a store, as in the query

`a = scan(smallTable);store(a, smallTable_curl);`

The relation smallTable is fine; it previously existed. The smallTable_curl relation does not exist. Yet the query returns SUCCESS.

**Comment by dhutchis** [comment] 2016-08-11 21:12
Here is a clue from the logs:

```
16/08/11 17:07:37 INFO parallel.MasterSubQuery: Starting execution for query #1445.0
16/08/11 17:07:37 INFO parallel.Server: Worker #1 succeeded in executing query #1445.0.
16/08/11 17:07:37 INFO parallel.MasterSubQuery: Query #1445.0 executed for 0.073736731s
16/08/11 17:07:37 WARN concurrent.OperationFutureBase: An exception was thrown by OperationFutureListener.
edu.washington.escience.myria.coordinator.CatalogException: java.util.concurrent.ExecutionException: edu.washington.escience.myria.coordinator.CatalogException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() INSERT INTO rel
ation_schema(user_name,program_name,relation_name,col_index,col_name,col_type,is_indexed,is_ascending_index) VALUES (?,?,?,?,?,?,?,?); [table relation_schema has no column named is_indexed]
        at edu.washington.escience.myria.coordinator.MasterCatalog.updateRelationMetadata(MasterCatalog.java:1821)
        at edu.washington.escience.myria.parallel.DatasetMetadataUpdater.operationComplete(DatasetMetadataUpdater.java:77)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:582)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyPreListeners(OperationFutureBase.java:563)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:144)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setSuccess0(OperationFutureBase.java:482)
        at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setSuccess(LocalSubQueryFuture.java:58)
        at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:105)
        at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:582)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:541)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
        at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setSuccess0(OperationFutureBase.java:482)
        at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setSuccess(LocalSubQueryFuture.java:58)
        at edu.washington.escience.myria.parallel.MasterSubQuery.workerComplete(MasterSubQuery.java:324)
        at edu.washington.escience.myria.parallel.QueryManager.workerComplete(QueryManager.java:307)
        at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
Caused by: java.util.concurrent.ExecutionException: edu.washington.escience.myria.coordinator.CatalogException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() INSERT INTO relation_schema(user_name,program_name,relation_name,col_index,col_name,col_type,is_indexed,is_ascending_index) VALUES (?,?,?,?,?,?,?,?); [table relation_schema has no column named is_indexed]
        at com.almworks.sqlite4java.SQLiteJob.get(SQLiteJob.java:329)
        at com.almworks.sqlite4java.SQLiteJob.get(SQLiteJob.java:283)
        at edu.washington.escience.myria.coordinator.MasterCatalog.updateRelationMetadata(MasterCatalog.java:1819)
        ... 21 more
Caused by: edu.washington.escience.myria.coordinator.CatalogException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() INSERT INTO relation_schema(user_name,program_name,relation_name,col_index,col_name,col_type,is_indexed,is_ascending_index) VALUES (?,?,?,?,?,?,?,?); [table relation_schema has no column named is_indexed]
        at edu.washington.escience.myria.coordinator.MasterCatalog.addRelationMetadata(MasterCatalog.java:412)
        at edu.washington.escience.myria.coordinator.MasterCatalog.access$1000(MasterCatalog.java:64)
        at edu.washington.escience.myria.coordinator.MasterCatalog$24.job(MasterCatalog.java:1793)
        at edu.washington.escience.myria.coordinator.MasterCatalog$24.job(MasterCatalog.java:1778)
        at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
        at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
        at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
        at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
        at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
        at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() INSERT INTO relation_schema(user_name,program_name,relation_name,col_index,col_name,col_type,is_indexed,is_ascending_index) VALUES (?,?,?,?,?,?,?,?); [table relation_schema has no column named is_indexed]
        at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
        at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:580)
        at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:635)
        at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:622)
        at edu.washington.escience.myria.coordinator.MasterCatalog.addRelationMetadata(MasterCatalog.java:394)
        ... 10 more
16/08/11 17:07:37 INFO coordinator.MasterCatalog: Finishing subquery 1445.0
16/08/11 17:07:37 INFO coordinator.MasterCatalog: Subquery #1445.0 succeeded. Time elapsed: 0.073736731s.
```

**Comment by dhutchis** [comment] 2016-08-11 21:14
Indeed the SQLite table `relation_schema` has no column named `is_indexed`.  Here is the schema of that table:

```sql
CREATE TABLE relation_schema (
    user_name TEXT NOT NULL,
    program_name TEXT NOT NULL,
    relation_name TEXT NOT NULL,
    col_index INTEGER NOT NULL,
    col_name TEXT,
    col_type TEXT NOT NULL,
    FOREIGN KEY (user_name,program_name,relation_name) REFERENCES relations ON DELETE CASCADE);
```

**Comment by jingjingwang** [comment] 2016-08-11 21:15
Which branch were you working on? Master branch has `is_indexed`.

**Comment by jingjingwang** [comment] 2016-08-11 21:16
But anyway I believe if you restart everything with scratch, the problem should be gone. Meanwhile we should check that null in `doIngest`.

**Comment by dhutchis** [comment] 2016-08-11 21:18
I was using the `master` branch as of a month ago. Maybe something changed since then? 

Yes, it appears I should blow away the cluster and start from scratch. I'm not sure what the cleanest way to do that is. Delete the deployment directory and the Postgres databases, and clear HDFS?

**Comment by jortiz16** [comment] 2016-08-11 21:18
```is_indexed``` was introduced about 15 days ago. If you had an old commit and updated, this might be why you're having this issue

**Comment by jingjingwang** [comment] 2016-08-11 21:20
I think `./gradlew clean shadowJar` is enough once you are with the latest master branch. It's only a change to catalog.

**Comment by dhutchis** [comment] 2016-08-11 21:26
Can I do something like 

```sql
ALTER TABLE relation_schema
ADD  is_indexed INTEGER NOT NULL DEFAULT 0, 
is_ascending_index INTEGER DEFAULT 0
```

or is this not enough to repair sqlite to the latest version?

**Comment by jingjingwang** [comment] 2016-08-11 21:28
You can have a try, I'm not sure if it will cover all the differences between your branch and master branch though. But if it works, it works :)

**Comment by dhutchis** [comment] 2016-08-11 21:30
In the future, I hope Myria supports versioning and releases...

**Comment by dhutchis** [comment] 2016-08-11 21:31
This appears to have worked.

**Comment by senderista** [comment] 2016-08-15 18:19
Closing this issue since the root cause is addressed in https://github.com/uwescience/myria/issues/846

**Closed by senderista** 2016-08-15 18:19 UTC
